version: '3'

services:

  nginx-service:
    image: nginx:latest
    container_name: nginx-service-container
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/app:/usr/share/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - multi-tenant-net

  city-service:
    image: openjdk-with-wfi:1.0
    restart: always
    container_name: city-service-container
    ports:
      - 8081:8081
    volumes:
      - ./target:/target
    command: java -jar -Dspring.profiles.active=docker target/city-service-db-style-0.0.1-SNAPSHOT.jar
    networks:
      - multi-tenant-net

  mssql-service:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    container_name: myssql-service-container
    volumes:
      - ./docker/mssql:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Lumia435@
    ports:
      - 33064:1433
    networks:
      - multi-tenant-net

  mysql-service:
    image: mysql:5.7
    container_name: mysql-service-container
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - 33061:3306
    networks:
      - multi-tenant-net

  h2db-service:
    image: joedoe/h2db
    container_name: h2db-service-container
    volumes:
      - ./docker/h2db:/data
    ports:
      - 81:81
      - 33063:1521
    networks:
      - multi-tenant-net

  postgres-service:
    image: postgres:9.6.17
    container_name: postgres-service-container
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=awhjw
    ports:
      - 33062:5432
    networks:
      - multi-tenant-net

networks:
  multi-tenant-net:
    driver: bridge
